global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prometheus-grafana-exporter'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'kafka'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['kafkaexporter:9308']